### ISSUE TITLE
[2.0] gulp-notify error in windows

### ISSUE THREAD

**Issue by AminulBD** [vigetlabs/gulp-starter#144]
Hi,

Today I just moved to do some task in windows. Everything's working fine in windows, but the gulp-notify not working with the gulp starter package.

Here is error:

````
[04:14:02] Starting 'sass'...
[04:14:02] gulp-notify: [Error running Gulp] Error in plugin 'gulp-sass'
Message:
    style declaration must contain a value
Details:
    fileName:
D:/Projects/appsworld/app/assets/stylesheets/base/_defaults.sass
    lineNumber:
28
[04:14:02] Finished 'sass' after 21 ms
[04:14:02] gulp-notify: [Error running notifier] Could not send message: Command failed: D:\Projects\appsworld\node_modu
les\gulp-notify\node_modules\node-notifier\vendor\toaster\toast.exe -sound Frog -p D:\Projects\appsworld\node_modules\gu
lp-notify\assets\gulp-error.png -m Error in plugin 'gulp-sass'
Message:
    style declaration must contain a value
Details:
    fileName:
D:/Projects/appsworld/app/assets/stylesheets/base/_defaults.sass
    lineNumber:
28 -t Error running Gulp

Unhandled Exception: System.Exception: Exception from HRESULT: 0xC00CE508
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at toast.Program.ShowToast(String title, String message, String imageURI)
   at toast.Program.Main(String[] args)

[04:14:07] Starting 'sass'...
[04:14:07] gulp-notify: [Error running Gulp] Error in plugin 'gulp-sass'
Message:
    file to import not found or unreadable:
base/defaults
Current dir:
D:/Projects/appsworld/app/assets/stylesheets/
Details:
    fileName:
D:/Projects/appsworld/app/assets/stylesheets/app.sass
    lineNumber:
4
[04:14:07] Finished 'sass' after 12 ms
[04:14:07] gulp-notify: [Error running notifier] Could not send message: Command failed: D:\Projects\appsworld\node_modu
les\gulp-notify\node_modules\node-notifier\vendor\toaster\toast.exe -sound Frog -p D:\Projects\appsworld\node_modules\gu
lp-notify\assets\gulp-error.png -m Error in plugin 'gulp-sass'
Message:
    file to import not found or unreadable:
base/defaults
Current dir:
D:/Projects/appsworld/app/assets/stylesheets/
Details:
    fileName:
D:/Projects/appsworld/app/assets/stylesheets/app.sass
    lineNumber:
4 -t Error running Gulp

Unhandled Exception: System.Exception: Exception from HRESULT: 0xC00CE508
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at toast.Program.ShowToast(String title, String message, String imageURI)
   at toast.Program.Main(String[] args)

````

**Comment by AminulBD** [comment]
Normally it's working when put example notification by reading docs: https://www.npmjs.com/package/gulp-notify

**Comment by AminulBD** [comment]
For now, I modified  handleErrors.js file. I removed some codes to get only notification.

````
module.exports = function(errorObject, callback) {
  notify.onError(errorObject).apply(this, arguments);
  // Keep gulp from hanging on this task
  if (typeof this.emit === 'function') this.emit('end');
};
````

**Comment by greypants** [comment]
I'll look into this. Thanks.
