### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by derrelldurrett** [vigetlabs/gulp-starter#228]
Attached is the npm-debug.log. I ran ```npm install```, then ```npm run gulp```.

If the problem is likely configuration on my end, please let me know what further info would help. I'm quite new to gulp.

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/derrell/INSTALLS/node-v4.2.1-linux-x64/bin/node',
1 verbose cli   '/home/derrell/bin/npm',
1 verbose cli   'run',
1 verbose cli   'gulp' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info pregulp gulp-starter@2.2.0
6 info gulp gulp-starter@2.2.0
7 verbose unsafe-perm in lifecycle true
8 info gulp-starter@2.2.0 Failed to exec gulp script
9 verbose stack Error: gulp-starter@2.2.0 gulp: `gulp`
9 verbose stack Exit status 7
9 verbose stack     at EventEmitter.<anonymous> (/home/derrell/INSTALLS/node-v4.2.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/derrell/INSTALLS/node-v4.2.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid gulp-starter@2.2.0
11 verbose cwd /home/derrell/RubymineProjects/ComicStripApp
12 error Linux 3.13.0-73-generic
13 error argv "/home/derrell/INSTALLS/node-v4.2.1-linux-x64/bin/node" "/home/derrell/bin/npm" "run" "gulp"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error gulp-starter@2.2.0 gulp: `gulp`
17 error Exit status 7
18 error Failed at the gulp-starter@2.2.0 gulp script 'gulp'.
18 error This is most likely a problem with the gulp-starter package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get their info via:
18 error     npm owner ls gulp-starter
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by greypants** [comment]
if I had to guess, it's `using node@v4.2.1`. I haven't tested these tools on node 4 yet... I need to! See https://github.com/vigetlabs/gulp-starter/blob/master/package.json#L6 for what this is meant to run on. any 0.12.x should run fine.

I'll add an issue for Node 4.x

**Comment by greypants** [comment]
Hmm. I can't seem to reproduce the error. I'm able to run things fine locally on node v4.2.1. Did you ever get this working?

**Comment by greypants** [comment]
Looks like this popped up for someone else: #236

**Comment by greypants** [comment]
I locked down exact dependencies in my `package.json` file to eliminate some variables. Did you ever get this working? Can you try again with the latests from `master`?
