### ISSUE TITLE
Example with React?

### ISSUE THREAD

**Issue by voodee** [vigetlabs/gulp-starter#270]
I try to connect React according to the instructions https://github.com/gaearon/react-transform-hmr
But I have error:

```
Module build failed: SyntaxError: .../src/javascripts/modules/editor.js: Unexpected token (8:11)

at Parser.pp.raise (.../node_modules/babylon/index.js:1378:13)
at Parser.pp.unexpected (.../node_modules/babylon/index.js:2817:8)
at Parser.pp.parseExprAtom (.../node_modules/babylon/index.js:749:12)
at Parser.pp.parseExprSubscripts (.../node_modules/babylon/index.js:504:19)
at Parser.pp.parseMaybeUnary (.../node_modules/babylon/index.js:484:19)
at Parser.pp.parseExprOps (.../node_modules/babylon/index.js:415:19)
at Parser.pp.parseMaybeConditional (.../node_modules/babylon/index.js:397:19)
at Parser.pp.parseMaybeAssign (.../node_modules/babylon/index.js:360:19)
at Parser.pp.parseExpression (.../node_modules/babylon/index.js:324:19)
at Parser.pp.parseReturnStatement (.../node_modules/babylon/index.js:2030:26)
 @ ./src/javascripts/modules ^\.\/.*$
```

**Comment by greypants** [comment]
Did you add the `react` babel preset?  

https://babeljs.io/docs/plugins/preset-react/

Install that, then add `'react'` to the preset list here: https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/config.json#L27

**Comment by greypants** [comment]
I would like to add a fully set up react demo to the extras folder at some point.

**Comment by voodee** [comment]
Thank you so works!

> I would like to add a fully set up react demo to the extras folder at some point.

It is a good idea)
