### ISSUE TITLE
Issue running production

### ISSUE THREAD

**Issue by stu-fu** [vigetlabs/gulp-starter#292]
Hi, I'm receiving this error when trying to run production:

```
[15:49:18] gulp-notify: [Error running Gulp] ModuleBuildError:
Module build failed:
TypeError:
Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /Users/StuFurlong/Desktop/Test Project/MyApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /Users/StuFurlong/Desktop/Test Project/MyApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/StuFurlong/Desktop/Test Project/MyApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/StuFurlong/Desktop/Test Project/MyApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/StuFurlong/Desktop/Test Project/MyApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /Users/StuFurlong/Desktop/Test Project/MyApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /Users/StuFurlong/Desktop/Test Project/MyApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
```

Running latest Node (6) and NPM (3.8.6)

**Comment by stu-fu** [comment]
Issue is with Node 6 - downgraded to 4.4.4 and running production works fine now

**Comment by jhabdas** [comment]
Engines are specified in the manifest but I hit the same issue as well. Backed down to node 5 and all is well. This issue can be closed.

**Comment by greypants** [comment]
I could add a .nvmrc file too. Does an issue need to be opened to support node 6? Probably.

**Comment by allyraza** [comment]
it would be nice to have support for node 6
