### ISSUE TITLE
How to fix error?? 

### ISSUE THREAD

**Issue by vijaykolar** [vigetlabs/gulp-starter#297]
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.

\\?\C:\Users\Vijay\AppData\Roaming\npm\node_modules\node-sass\vendor\win32-x64-46\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Vijay\AppData\Roaming\npm\node_modules\node-sass\lib\index.js:23:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by greypants** [comment]
Not sure how to help, as I don't have windows running. @chaelli has a lot of experience with this project on Windows though. He'd be a good person to ping if you're still having issues. If you've figured it out, definitely post your solution here.

**Comment by vijaykolar** [comment]
@greypants Thanks for your reply. I have fixed this issue.

**Comment by Tatenda** [comment]
@vijaykolar how did you fix it. Facing same problem
