### ISSUE TITLE
Problem to run NPM start

### ISSUE THREAD

**Issue by raisiqueira** [vigetlabs/gulp-starter#308]
![captura de tela de 2016-07-15 17-01-47](https://cloud.githubusercontent.com/assets/2914170/16887000/e56234da-4aad-11e6-9a6f-247afea9512c.png)

**Comment by andrewcaulfield** [comment]
+1 with this issue
<img width="888" alt="screen shot 2016-07-19 at 20 40 53" src="https://cloud.githubusercontent.com/assets/3205699/16964016/28b0a3f2-4df1-11e6-8cd7-233f99290113.png">

**Comment by raisiqueira** [comment]
I'm using node 6.2.2 in the development and production server. But it does not work when running NPM START or NPM RUN PRODUCTION

**Comment by greypants** [comment]
can you guys post the full output you're getting? Both screenshots cut off the important information.

**Comment by raisiqueira** [comment]
**NPM INSTALL**
```
root@ubuntu-1gb-sfo1-01:~/newfront# npm install
root@ubuntu-1gb-sfo1-01:~/newfront# npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global varstream@0.3.2 should be installed with -g
npm WARN prefer global svgicons2svgfont@5.0.0 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global ttf2woff2@2.0.3 should be installed with -g

> bufferutil@1.2.1 install /root/newfront/node_modules/bufferutil
> node-gyp rebuild

root@ubuntu-1gb-sfo1-01:~/newfront#
```

**NPM START**
```
root@ubuntu-1gb-sfo1-01:~/newfront# npm start

> gulp-starter@3.1.0 start /root/newfront
> gulp

(node:32127) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/root/newfront/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/root/newfront/node_modules/node-sass/lib/extensions.js:119:13)
    at foundBinariesList (/root/newfront/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/newfront/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/newfront/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/root/newfront/node_modules/node-sass/lib/index.js:15:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/root/.nvm/versions/node/v6.3.0/bin/node" "/root/.nvm/versions/node/v6.3.0/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! gulp-starter@3.1.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gulp-starter@3.1.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gulp-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gulp-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gulp-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/newfront/npm-debug.log
root@ubuntu-1gb-sfo1-01:~/newfront#
```

**Comment by greypants** [comment]
```
npm ERR! node v6.3.0
```

Node 6 is not yet supported. See #302
