### ISSUE TITLE
Gulp-Starter does not work with nodejs 6.5 and npm 3.10.3

### ISSUE THREAD

**Issue by interglobalmedia** [vigetlabs/gulp-starter#323]
Gulp-Starter does not work with nodejs 6.5 and npm 3.10.3. I get the following errors in Terminal:
gulp-starter@3.1.0 gulp /Users/mariacam/Development/tic-tac-toe/xoApp
gulp

(node:17803) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:15
    throw new Error(errors.missingBinary());
    ^

Error: Missing binding /Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:15:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/gulp-sass/index.js:186:21)
    at Module._compile (module.js:556:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! gulp-starter@3.1.0 gulp: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gulp-starter@3.1.0 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gulp-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gulp-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gulp-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mariacam/Development/tic-tac-toe/xoApp/npm-debug.log

**Comment by interglobalmedia** [comment]
I rebuilt node sass and it's working now. Issue closed.
