### ISSUE TITLE
`babel-core` throwing error on `npm start`

### ISSUE THREAD

**Issue by roytruelove** [vigetlabs/gulp-starter#343]
I'm seeing the following when running `npm start` off of the tip of `master`:

```
ERROR in ./src/javascripts/app.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at /home/roy/src/hollandanalytics/kapevo-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /home/roy/src/hollandanalytics/kapevo-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/home/roy/src/hollandanalytics/kapevo-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/home/roy/src/hollandanalytics/kapevo-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/home/roy/src/hollandanalytics/kapevo-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /home/roy/src/hollandanalytics/kapevo-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /home/roy/src/hollandanalytics/kapevo-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
 @ multi app
```

Will be doing some digging to see if I can pin it down.

**Comment by roytruelove** [comment]
Wiping out `node_modules` and re-`npm install`-ing did the trick.  Closing.
